# Generated by Django 5.1 on 2024-08-24 05:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('last_priced_date', models.DateField()),
                ('tnx_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Div', 'Div')], max_length=5)),
                ('quantity', models.FloatField()),
                ('txn_price', models.FloatField()),
                ('txn_date', models.DateField()),
                ('last_price', models.FloatField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
