# Generated by Django 5.1 on 2024-08-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='last_priced_date',
            field=models.DateField(null=True),
        ),
    ]
