# Generated by Django 5.1 on 2024-08-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_alter_share_last_priced_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='last_price',
            field=models.FloatField(null=True),
        ),
    ]
