# Generated by Django 5.1 on 2024-08-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_alter_share_last_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='share',
            name='last_priced_date',
        ),
    ]
